name: Rust

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - v*.*.*
  pull_request: {}

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: update rust stable
        run: rustup update stable
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose