name: Rust

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - v*.*.*
  pull_request: {}

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    timeout-minutes: 5
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: configure rustup
        run: |
          rustup update stable
          rustup target add x86_64-pc-windows-gnu
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: | 
          py -m venv venv
          venv\Scripts\activate
          pip install ahk-binary
          cargo test --verbose
